name: learning-pareto
channels:
- defaults
- conda-forge
- pytorch
dependencies:
- python=3.7.*
- cudatoolkit=10.2.*
- matplotlib=3.4.*
- numpy=1.19.*
- pandas=1.3.*
- pip=21.2.*
- pytorch=1.10.*
- scikit-garden=0.1.*
- scikit-learn=0.22.*
- scipy=1.6.*
- seaborn=0.11.*
- setuptools=58.0.*
- pip:
  - nonconformist==2.1.*